site_name: Lwabish-Notes
repo_name: lwabish/notes
repo_url: https://github.com/lwabish/notes
copyright: Copyright &copy; 2014 - 2022 Lwabish
theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    primary: indigo
  language: zh
  features:
    - navigation.expand
    - toc.integrate
    - navigation.top
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
