apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Chart.Name }}"
spec:
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
      version: "{{ .Values.tag }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
        version: "{{ .Values.tag }}"
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.registry }}/notes:{{ .Values.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-conf
              subPath: nginx.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: notes-nginx-config